# Generated by Django 5.2.12 on 2026-03-05 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='core_studen_full_na_9eb4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_status'], name='core_studen_enrollm_04599d_idx'),
        ),
        migrations.AddField(
            model_name='studentvisitorrelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_relationships', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['full_name'], name='core_visito_full_na_17c6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['national_id_normalized'], name='core_visito_nationa_0cb3fd_idx'),
        ),
        migrations.AddField(
            model_name='studentvisitorrelationship',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='core.visitor'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='core.student'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='core.visitor'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name'], name='core_audit__model_n_960af7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_audit__timesta_ebe809_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id'], name='core_audit__user_id_cd8017_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentvisitorrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'visitor'), name='unique_student_visitor'),
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['visit_date'], name='core_visit__visit_d_315e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['check_out_time'], name='core_visit__check_o_773743_idx'),
        ),
    ]
